name: Build Windows x64
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Cache for faster build
      uses: actions/cache@v4.2.3
      with:
        path: Project/Library
        key: Library-Xiaozhi-Unity-Windows-x64
        restore-keys: |
          Library-Xiaozhi-Unity-
          Library-

    - name: Unity - Activate
      uses: game-ci/unity-activate@v2.0.0
      with:
        unityVersion: 2022.3.59f1
      
    - name: Unity - Builder
      uses: game-ci/unity-builder@v4.4.0
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        targetPlatform: StandaloneWindows64
        projectPath: Project
        buildMethod: XiaoZhi.Unity.Builder.BuildCI

    - name: Unity - Return License
      uses: game-ci/unity-return-license@v2.0.0
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Windows-x64
        path: Build/StandaloneWindows64
        
